### ISSUE TITLE
Add more functionality to save method

### ISSUE THREAD

**Issue by jackmoody11** [sec-edgar/sec-edgar#140]
**Is your feature request related to a problem? Please describe.**
Currently, the functionality of the `save` method is hard-coded and restrictive. It is very possible for filings to be saved however one likes using `get_filings_dict`; however, it may be better to have a more systematic approach to this that would allow users to define the structure of their directories in a more readable manner. Not sure if this should be left to the user to adjust.

**Describe the solution you'd like**
Maybe create directory pattern "language" that will allow others to choose how filings are saved using attributes about the filings (e.g. filing type, CIK, company name, date, quarter, year, month, etc.)

**Describe alternatives you've considered**
Leave it to the users to work with `get_filings_dict` and create their own logic.

**Comment by reteps** [comment]
This is kind of a tricky problem, since the user doesn't really know anything about the properties of the filing system.

I am a big fan of user defined lambdas / functions, but in this case I think a format string would work better. Here is what I would propose (with my limited knowledge).

+ Make a `pattern` argument that overrides directory.

For example, a user could now use it like this:
```python3
master.save(directory='./files')
```
or like this:
```python3
master.save(directory, pattern='/{year}/QTR{quarter}/end')
```

And then it would be implemented like:
```
def save(self, directory, pattern='/{year}/QTR{quarter}/end', file_pattern='{company}'):
    formatted_path = split(pattern.format(self.year, self.quarter, ....), os.seperator) # something like that
    path = os.path.join(directory, full_pattern)
    self.save_filings(directory, file_pattern)
```

```
    def save_filings(self, directory, pattern):
                full_pattern = pattern.format(COMPANY_ID)
                path = os.path.join(directory, full_pattern)
                make_path(path)
                path = os.path.join(path, self.get_accession_number(link))
```
   
https://github.com/sec-edgar/sec-edgar/blob/639c0b75f51d3f5536ee6e4effd636047f6d5c5a/secedgar/filings/_index.py#L158

This is the part we want to modify:
```python3
path = os.path.join(directory, company)
```

**Comment by jackmoody11** [comment]
@reteps this is a really clean solution!
