### ISSUE TITLE
Simplified API

### ISSUE THREAD

**Issue by jackmoody11** [sec-edgar/sec-edgar#157]
**Is your feature request related to a problem? Please describe.**
@reteps had brought this up to me and I think he makes a good point. There is no need for the end user to have to create separate `DailyFilings`, `MasterFilings`, and `Filing` objects. There should just be a single `Filings` object that uses some basic logic to delegate tasks to the correct class.

**Describe the solution you'd like**
Some sort of API where the initialization would look like this:\

```python
class Filings(AbstractFiling):
    def __init__(self, start_date, end_date, cik_lookup=None, filing_type=None):
        ...
```

Where if `None` given for `cik_lookup` or `filing_type`, all would be searched for. 

**Describe alternatives you've considered**

- Keep as is. This would reduce size of code base, but would make it harder to use the package.

**Comment by reteps** [comment]
I thought about this for a while, as this is really a tricky problem. I have decided that this is my favorite example:

```python3
from edgar import Filings, FilingTypes

query = Filings(2020, 2021, 'appl', filing_types=['4'])

for document_group in query.get_documents(as_iterator=True, filter_fn=lambda x:x.type == '4'):
    pass
```

The bottom line is that the current inheritance pattern sucks. A `DailyFiling` and `Filing` have almost nothing in common except functionality, so **the required functionality should be inherited, not what they have in common**. This means that the `AbstractFiling` will be replaced by `FilingEngine`.

I imagine that all the engines will contain these basic methods:
+ saving text files
+ saving documents
+ retrieving documents
+ saving search results
+ getting search results

```python3
class FilingEngine:

    client = NetworkClient()

    ''' save the text files from each result '''
    def save_text_files(directory, dir_pattern=None, file_pattern=None):
        self.engine.save_text_files(**kwargs)
    '''save documents in index filings matching criterion. First requests index for file list.'''
    def save_documents(directory, dir_pattern=None, file_pattern=None, filter_fn=None):
        pass
    ''' get document list in index filings matching criterion. '''
    def get_documents(filter_fn=None, as_iterator=False):
        pass
    ''' download the results as a tsv. If results are not a tsv / from an index list, convert to a tsv. '''
    def save_results(file_name):
        pass
    ''' return a list of the results.'''
    def get_results(as_iterator=True):
        pass
```
Then, a superclass will return the relevant class based on user inputs:
```python3
class Filings:
    '''
    result_filter_fn: Filter the result list with a function
    '''
    def __init__(self, date, end_date=None, companies=None, filing_types=None, result_filter_fn=None, maximum_results=None):
        if companies is None:
            if end_date is None:
                return DailyFilings()

            return MasterFilings()
        return StandardFilings()
```
Next, the network client. The purpose of this class is more to encapsulate functionality rather than to provide anything useful by being a class. In its current state, this is not ideal because

+ The user will almost never modify it
+ The seperation of logic from the main filing classes and making requests is confusing. the whole point of the filing class is to make requests, so why seperate things that are so closely intertwined together without being very clear what the methods do and flipping between the classes.

~~**Turning this class into just 3 methods it has is ideal because you do not need to encapsulate functionality if there is only 3 methods being called!**~~

On second thought, just remove the `base` network_client class as I can't imagine anyone modifying it and clarify some of the methods, e.g.

+ `get_response(self, path, params, **kwargs)` could be renamed to `get_response(self, url, url_params, **kwargs)`.

Next, the CIK Lookup.

+ Why is this in 2 classes? "CIK Validator Used internally by CIK Lookup" - just make it one class, `CIKLookup`!

Next, the AbstractFiling class. A combination of helper methods and abstract properties already mentioned above. Move `clean_directory_path` to util. 


At the end of rework,

```
network_client.py
filing_engine.py
daily.py
index.py
master.py
standard.py
filings.py
filing_types.py
cik_lookup.py
```

Removing the client base and combining the cik_lookup and cik_validator together. Replacing the `AbtractFiling` with `FilingEngine`. Creating a class factory? `Filings`.

**Comment by jackmoody11** [comment]
Thanks for your thoughts on this @reteps. This gives me a lot to think about. Will work on drawing up a reworked API to try to address some of these issues.
