### ISSUE TITLE
RuntimeError: This event loop is already running - on the code from README

### ISSUE THREAD

**Issue by President** [sec-edgar/sec-edgar#191]
**Describe the bug**
Example code from README is not working

**To Reproduce**

Just run the code from README:

```
!pip install secedgar
from secedgar.filings import Filing, FilingType
# 10Q filings for Apple (ticker "aapl")
my_filings = Filing(cik_lookup='aapl', filing_type=FilingType.FILING_10Q)
my_filings.save('.')
```

And you will see the error:

```
<ipython-input-13-df0354d1a1e3> in <module>
      1 # 10Q filings for Apple (ticker "aapl")
      2 my_filings = Filing(cik_lookup='aapl', filing_type=FilingType.FILING_10Q)
----> 3 my_filings.save('.')

~/Coding/trading-platform/python/venv2/lib/python3.8/site-packages/secedgar/filings/filing.py in save(self, directory, dir_pattern, file_pattern)
    222 
    223         loop = asyncio.get_event_loop()
--> 224         loop.run_until_complete(self.client.wait_for_download_async(inputs))

~/.pyenv/versions/3.8.7/lib/python3.8/asyncio/base_events.py in run_until_complete(self, future)
    590         """
    591         self._check_closed()
--> 592         self._check_running()
    593 
    594         new_task = not futures.isfuture(future)

~/.pyenv/versions/3.8.7/lib/python3.8/asyncio/base_events.py in _check_running(self)
    550     def _check_running(self):
    551         if self.is_running():
--> 552             raise RuntimeError('This event loop is already running')
    553         if events._get_running_loop() is not None:
    554             raise RuntimeError(

RuntimeError: This event loop is already running
```

**Expected behavior**
I expect that code from README should work

**Desktop (please complete the following information):**
OS X 11.2.3

**Comment by jackmoody11** [comment]
I think we need to close the loop as is outlined in [this Stack Overflow question](https://stackoverflow.com/questions/41231399/necessity-of-closing-asyncio-event-loop-explicitly).

**Comment by khazaddim** [comment]
For me this is only happening in Jupyter notebook.   If I run in a .py file it works fine.

**Comment by khazaddim** [comment]
I'm on python 3.7 64 bit Ubuntu 20.04

**Comment by jackmoody11** [comment]
@khazaddim @President I think this issue is caused by ipykernel [having a persistent asyncio loop running](https://ipython.readthedocs.io/en/stable/interactive/autoawait.html#difference-between-terminal-ipython-and-ipykernel). You can [read about workarounds here](https://github.com/ipython/ipython/issues/11338).

Using the latest version of secedgar, I got the same RuntimeError, but interestingly the filings were still downloaded.

For now, I would suggest either using the workarounds suggested above or running your scripts to download data from the command line or from .py files.

If these solutions aren't feasible for some reason, please let me know. Will close this issue for now.
