### ISSUE TITLE
Use Case Example in Documentation

### ISSUE THREAD

**Issue by mksamelson** [sec-edgar/sec-edgar#91]
Could you put a use case in the the documentation using Filings but with a date range instead of a number of documents?

**Comment by jackmoody11** [comment]
This is not in the code yet, but I am working on it. We will change the filing class to take in a `start_date` and `end_date`. The start date will default to None so that if it isn't specified all filings before end date will be fetched. The end date will replace the dateb parameter (this is the same thing, but using end_date seems more straightforward).
